VIA_ENABLE = yes
VIAL_ENABLE = yes
VIAL_INSECURE = yes
CAPS_WORD_ENABLE = yes

KEY_LOCK_ENABLE = yes

AUTO_SHIFT_ENABLE   = yes
TAP_DANCE_ENABLE    = yes
RETRO_TAPPING_ENABLE = yes
RETRO_SHIFT_ENABLE  = yes
EXTRAKEY_ENABLE = yes
CAPS_WORD_ENABLE = yes
